### ISSUE TITLE
[PE-D][Tester A] `removetagall` removes the `participation score` of all contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-1/tp#119] opened 2024-04-05 20:09 UTC
![image.png](https://raw.githubusercontent.com/AidenLYT/ped/main/files/1e7b9b10-7170-4d67-8f68-9a239ff0c41a.png)

![image.png](https://raw.githubusercontent.com/AidenLYT/ped/main/files/addaa537-6aa0-4f22-b015-bdb3c2d2cf54.png)

When an **invalid** tag was entered, all the participation score of the existing contacts were all wiped out.

## Steps to reproduce
- add 1 contact with tag `t/hello`
- add 1 contact with tag `t/hello t/okay`
- Run `markallp 1` command
- Run `removetagall t/nono` command

## Expected Output:
No such tags error 

## Actual Output: 
No such tags error **and all the participation scores reset to 0**

## Reason for severity: 
Invalid command caused existing command behavior to malfunction, wiping out important information (in this case participation score) of the existing contacts.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: AidenLYT/ped#9

**Comment by shawnnlimm** [comment] 2024-04-06 15:00
Duplicate of #134

**Closed as completed by shawnnlimm** 2024-04-06 15:00 UTC
Labels: type.Duplicate
