### ISSUE TITLE
[PE-D][Tester D] Undo Command Does Not Work for Grade Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-1/tp#107] opened 2024-04-05 19:00 UTC
Based on the UG, undo should undo commands that change data. However, this does not work for grade. It could be that the grade command was not saved in the command history? If grade is not meant to change data, then this is a feature flaw, as it works for adding assignment. Perhaps indicating which commands change the data (and thus can be undone) in the UG would also be helpul?

Steps to reproduce bug:
1. `adda a/HELLO`
2. `grade 1 20 a/HELLO`
3. `undo`

Expected: Undo undoes the grade command.
Actual: Undo undoes the command (add assignment in the example) before the grade command.

![image.png](https://raw.githubusercontent.com/getsquared/ped/main/files/8a43375d-9545-4c9b-bfd2-0b2e03bb885c.png)

![image.png](https://raw.githubusercontent.com/getsquared/ped/main/files/6f09e857-a6cd-4b6e-be55-eb046c567fb2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: getsquared/ped#4

**Comment by shawnnlimm** [comment] 2024-04-06 13:49
Duplicate of #104

**Closed as completed by shawnnlimm** 2024-04-06 13:49 UTC
Labels: type.Duplicate
